language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "pypy"
env:
    - DB=sqlite
    - DB=mysql
    - DB=pgsql

before_script:
    - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS ras_test;' -U postgres; fi"
    - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database ras_test;' -U postgres; fi"
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS ras_test;'; fi"

install:
    - pip install -q -r requirements.txt --use-mirrors
    - pip install -q --use-mirrors pep8
    - sh -c "if [ '$DB' = 'pgsql' ]; then pip install -q psycopg2 ; fi"
    - sh -c "if [ '$DB' = 'mysql' ]; then pip install -q mysql-python ; fi"

script:
    - ./tests/manage.py test RandoAmisSecours
    - pep8 --statistics RandoAmisSecours

# Exclude some combinations as:
# - mysql-python does not work under python3
# - psycopg2 does not work under pypy
matrix:
    exclude:
        - python: "3.3"
          env: DB=mysql
        - python: "pypy"
          env: DB=pgsql
